### ISSUE TITLE
Initialize app with start server

### ISSUE THREAD

**Issue by mgilangjanuar** [mgilangjanuar/py-simple-http-server#1]
I want user only initiate App for start server, maybe something like this:

```
...
app = App(__name__, port = 5000)

@app.route('/')
def route_index():
    return app.response.send('Hello, World!')
```

Please read `README.md` for contributing or installing.

**Comment by NdagiStanley** [comment]
I am willing to take this up but this issue is not very clear.
Please elaborate by framing it like this:
```
Given some precondition
When I do some action
Then I expect some result
```
