### ISSUE TITLE
Refactor getting data from request

### ISSUE THREAD

**Issue by mgilangjanuar** [mgilangjanuar/py-simple-http-server#2]
I want getting data from request like `data_post`, `data_get`, `data_json` more simple, maybe like:

```
app.request.data.get(param)
app.request.data.post(param)
app.request.data.json(param)
```

Feel free for discuss about your idea / suggestion.

**Comment by akshay-verma** [comment]
@mgilangjanuar I would like to give it a try!

**Comment by mgilangjanuar** [comment]
@akshay-verma okay, good luck!

**Comment by akshay-verma** [comment]
You already have 'app.request.data_post', what advantage will be there switching to 'app.request.data.post'?
